//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:51:41 AM IST 
//


package in.cdac.cryptoservice;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;



/**
 * <p>Java class for CustOpts complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustOpts">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ParaName" type="{http://www.cdac.in/cryptoservice}ParaName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustOpts", propOrder = {
    "paraNames"
})
public class CustOpts
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "ParaName")
    protected List<ParaName> paraNames;

    /**
     * Gets the value of the paraNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paraNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParaNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParaName }
     * 
     * 
     */
    public List<ParaName> getParaNames() {
        if (paraNames == null) {
            paraNames = new ArrayList<ParaName>();
        }
        return this.paraNames;
    }

    public boolean isSetParaNames() {
        return ((this.paraNames!= null)&&(!this.paraNames.isEmpty()));
    }

    public void unsetParaNames() {
        this.paraNames = null;
    }

}
