//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:51:41 AM IST 
//


package in.cdac.cryptoservice;

import java.io.Serializable;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataElement">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.cdac.in/cryptoservice>Base64Data">
 *       &lt;attribute name="refno" type="{http://www.cdac.in/cryptoservice}RefNumber" />
 *       &lt;attribute name="type" type="{http://www.cdac.in/cryptoservice}idtype" />
 *       &lt;attribute name="idexist" type="{http://www.cdac.in/cryptoservice}idtype" />
 *       &lt;attribute name="prn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataElement", propOrder = {
    "value"
})
public class DataElement
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlValue
    protected byte[] value;
    @XmlAttribute
    protected String refno;
    @XmlAttribute
    protected Idtype type;
    @XmlAttribute
    protected Idtype idexist;
    @XmlAttribute
    protected String prn;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setValue(byte[] value) {
        this.value = ((byte[]) value);
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

    /**
     * Gets the value of the refno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefno() {
        return refno;
    }

    /**
     * Sets the value of the refno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefno(String value) {
        this.refno = value;
    }

    public boolean isSetRefno() {
        return (this.refno!= null);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Idtype }
     *     
     */
    public Idtype getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Idtype }
     *     
     */
    public void setType(Idtype value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the idexist property.
     * 
     * @return
     *     possible object is
     *     {@link Idtype }
     *     
     */
    public Idtype getIdexist() {
        return idexist;
    }

    /**
     * Sets the value of the idexist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Idtype }
     *     
     */
    public void setIdexist(Idtype value) {
        this.idexist = value;
    }

    public boolean isSetIdexist() {
        return (this.idexist!= null);
    }

    /**
     * Gets the value of the prn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrn() {
        return prn;
    }

    /**
     * Sets the value of the prn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrn(String value) {
        this.prn = value;
    }

    public boolean isSetPrn() {
        return (this.prn!= null);
    }

}
