//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:51:41 AM IST 
//


package in.cdac.cryptoservice;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KeyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="aes"/>
 *     &lt;enumeration value="rsa2048envd"/>
 *     &lt;enumeration value="rsa2048"/>
 *     &lt;enumeration value="rsa2048hybd"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KeyType")
@XmlEnum
public enum KeyType {

    @XmlEnumValue("aes")
    AES("aes"),
    @XmlEnumValue("rsa2048envd")
    RSA_2048_ENVD("rsa2048envd"),
    @XmlEnumValue("rsa2048")
    RSA_2048("rsa2048"),
    @XmlEnumValue("rsa2048hybd")
    RSA_2048_HYBD("rsa2048hybd");
    private final String value;

    KeyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KeyType fromValue(String v) {
        for (KeyType c: KeyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
