//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:51:41 AM IST 
//


package in.cdac.cryptoservice;

import java.io.Serializable;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.cdac.in/cryptoservice}DataElement"/>
 *         &lt;element name="CustOpts" type="{http://www.cdac.in/cryptoservice}CustOpts" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ac" use="required" type="{http://www.cdac.in/cryptoservice}AuaCode" />
 *       &lt;attribute name="sa" use="required" type="{http://www.cdac.in/cryptoservice}SubAuaCode" />
 *       &lt;attribute name="opr" use="required" type="{http://www.cdac.in/cryptoservice}Operations" />
 *       &lt;attribute name="tkntype" use="required" type="{http://www.cdac.in/cryptoservice}TokenType" />
 *       &lt;attribute name="keytype" type="{http://www.cdac.in/cryptoservice}KeyType" />
 *       &lt;attribute name="keyidentifier" type="{http://www.cdac.in/cryptoservice}KeyIdentifier" />
 *       &lt;attribute name="lk" type="{http://www.cdac.in/cryptoservice}UUID" />
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="txn" use="required" type="{http://www.cdac.in/cryptoservice}UUID" />
 *       &lt;attribute name="mac" use="required" type="{http://www.cdac.in/cryptoservice}macAddress" />
 *       &lt;attribute name="ip" use="required" type="{http://www.cdac.in/cryptoservice}ipAddress" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", propOrder = {
    "data",
    "custOpts"
})
@XmlRootElement(name = "request")
public class Request
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected DataElement data;
    @XmlElement(name = "CustOpts")
    protected CustOpts custOpts;
    @XmlAttribute(required = true)
    protected String ac;
    @XmlAttribute(required = true)
    protected String sa;
    @XmlAttribute(required = true)
    protected Operations opr;
    @XmlAttribute(required = true)
    protected TokenType tkntype;
    @XmlAttribute
    protected KeyType keytype;
    @XmlAttribute
    protected String keyidentifier;
    @XmlAttribute
    protected String lk;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ts;
    @XmlAttribute(required = true)
    protected String txn;
    @XmlAttribute(required = true)
    protected String mac;
    @XmlAttribute(required = true)
    protected String ip;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link DataElement }
     *     
     */
    public DataElement getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataElement }
     *     
     */
    public void setData(DataElement value) {
        this.data = value;
    }

    public boolean isSetData() {
        return (this.data!= null);
    }

    /**
     * Gets the value of the custOpts property.
     * 
     * @return
     *     possible object is
     *     {@link CustOpts }
     *     
     */
    public CustOpts getCustOpts() {
        return custOpts;
    }

    /**
     * Sets the value of the custOpts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustOpts }
     *     
     */
    public void setCustOpts(CustOpts value) {
        this.custOpts = value;
    }

    public boolean isSetCustOpts() {
        return (this.custOpts!= null);
    }

    /**
     * Gets the value of the ac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAc(String value) {
        this.ac = value;
    }

    public boolean isSetAc() {
        return (this.ac!= null);
    }

    /**
     * Gets the value of the sa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSa() {
        return sa;
    }

    /**
     * Sets the value of the sa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSa(String value) {
        this.sa = value;
    }

    public boolean isSetSa() {
        return (this.sa!= null);
    }

    /**
     * Gets the value of the opr property.
     * 
     * @return
     *     possible object is
     *     {@link Operations }
     *     
     */
    public Operations getOpr() {
        return opr;
    }

    /**
     * Sets the value of the opr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operations }
     *     
     */
    public void setOpr(Operations value) {
        this.opr = value;
    }

    public boolean isSetOpr() {
        return (this.opr!= null);
    }

    /**
     * Gets the value of the tkntype property.
     * 
     * @return
     *     possible object is
     *     {@link TokenType }
     *     
     */
    public TokenType getTkntype() {
        return tkntype;
    }

    /**
     * Sets the value of the tkntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenType }
     *     
     */
    public void setTkntype(TokenType value) {
        this.tkntype = value;
    }

    public boolean isSetTkntype() {
        return (this.tkntype!= null);
    }

    /**
     * Gets the value of the keytype property.
     * 
     * @return
     *     possible object is
     *     {@link KeyType }
     *     
     */
    public KeyType getKeytype() {
        return keytype;
    }

    /**
     * Sets the value of the keytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyType }
     *     
     */
    public void setKeytype(KeyType value) {
        this.keytype = value;
    }

    public boolean isSetKeytype() {
        return (this.keytype!= null);
    }

    /**
     * Gets the value of the keyidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyidentifier() {
        return keyidentifier;
    }

    /**
     * Sets the value of the keyidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyidentifier(String value) {
        this.keyidentifier = value;
    }

    public boolean isSetKeyidentifier() {
        return (this.keyidentifier!= null);
    }

    /**
     * Gets the value of the lk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLk() {
        return lk;
    }

    /**
     * Sets the value of the lk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLk(String value) {
        this.lk = value;
    }

    public boolean isSetLk() {
        return (this.lk!= null);
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTs(XMLGregorianCalendar value) {
        this.ts = value;
    }

    public boolean isSetTs() {
        return (this.ts!= null);
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxn(String value) {
        this.txn = value;
    }

    public boolean isSetTxn() {
        return (this.txn!= null);
    }

    /**
     * Gets the value of the mac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMac() {
        return mac;
    }

    /**
     * Sets the value of the mac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMac(String value) {
        this.mac = value;
    }

    public boolean isSetMac() {
        return (this.mac!= null);
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIp() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIp(String value) {
        this.ip = value;
    }

    public boolean isSetIp() {
        return (this.ip!= null);
    }

}
