//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.06 at 09:51:41 AM IST 
//


package in.cdac.cryptoservice;

import java.io.Serializable;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" type="{http://www.cdac.in/cryptoservice}DataElement"/>
 *         &lt;element name="CustOpts" type="{http://www.cdac.in/cryptoservice}CustOpts"/>
 *       &lt;/sequence>
 *       &lt;attribute name="keyidentifier" type="{http://www.cdac.in/cryptoservice}KeyIdentifier" />
 *       &lt;attribute name="error" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://www.cdac.in/cryptoservice}Status" />
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="txn" use="required" type="{http://www.cdac.in/cryptoservice}UUID" />
 *       &lt;attribute name="respid" use="required" type="{http://www.cdac.in/cryptoservice}UUID" />
 *       &lt;attribute name="keytype" type="{http://www.cdac.in/cryptoservice}KeyType" />
 *       &lt;attribute name="userscheme" type="{http://www.cdac.in/cryptoservice}userScheme" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "data",
    "custOpts"
})
@XmlRootElement(name = "response")
public class Response
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected DataElement data;
    @XmlElement(name = "CustOpts", required = true)
    protected CustOpts custOpts;
    @XmlAttribute
    protected String keyidentifier;
    @XmlAttribute(required = true)
    protected String error;
    @XmlAttribute(required = true)
    protected Status status;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ts;
    @XmlAttribute(required = true)
    protected String txn;
    @XmlAttribute(required = true)
    protected String respid;
    @XmlAttribute
    protected KeyType keytype;
    @XmlAttribute
    protected String userscheme;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link DataElement }
     *     
     */
    public DataElement getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataElement }
     *     
     */
    public void setData(DataElement value) {
        this.data = value;
    }

    public boolean isSetData() {
        return (this.data!= null);
    }

    /**
     * Gets the value of the custOpts property.
     * 
     * @return
     *     possible object is
     *     {@link CustOpts }
     *     
     */
    public CustOpts getCustOpts() {
        return custOpts;
    }

    /**
     * Sets the value of the custOpts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustOpts }
     *     
     */
    public void setCustOpts(CustOpts value) {
        this.custOpts = value;
    }

    public boolean isSetCustOpts() {
        return (this.custOpts!= null);
    }

    /**
     * Gets the value of the keyidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyidentifier() {
        return keyidentifier;
    }

    /**
     * Sets the value of the keyidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyidentifier(String value) {
        this.keyidentifier = value;
    }

    public boolean isSetKeyidentifier() {
        return (this.keyidentifier!= null);
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    public boolean isSetError() {
        return (this.error!= null);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return (this.status!= null);
    }

    /**
     * Gets the value of the ts property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTs(XMLGregorianCalendar value) {
        this.ts = value;
    }

    public boolean isSetTs() {
        return (this.ts!= null);
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxn(String value) {
        this.txn = value;
    }

    public boolean isSetTxn() {
        return (this.txn!= null);
    }

    /**
     * Gets the value of the respid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespid() {
        return respid;
    }

    /**
     * Sets the value of the respid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespid(String value) {
        this.respid = value;
    }

    public boolean isSetRespid() {
        return (this.respid!= null);
    }

    /**
     * Gets the value of the keytype property.
     * 
     * @return
     *     possible object is
     *     {@link KeyType }
     *     
     */
    public KeyType getKeytype() {
        return keytype;
    }

    /**
     * Sets the value of the keytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyType }
     *     
     */
    public void setKeytype(KeyType value) {
        this.keytype = value;
    }

    public boolean isSetKeytype() {
        return (this.keytype!= null);
    }

    /**
     * Gets the value of the userscheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserscheme() {
        return userscheme;
    }

    /**
     * Sets the value of the userscheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserscheme(String value) {
        this.userscheme = value;
    }

    public boolean isSetUserscheme() {
        return (this.userscheme!= null);
    }

}
